maintainer        "Mynewsdesk"
maintainer_email  "dev@mynewsdesk.com"
license           "MIT"
description       "Install Alfred"
version           "1.0.1"
supports          "mac_os_x"
depends           "zip"
