maintainer        "n1ko"
maintainer_email  "n1ko@salaliitto.com"
license           "MIT"
description       "Install Sourcetree"
version           "1.0.0"
supports          "mac_os_x"
depends           "dmg"
